version: '3.8'

volumes:
  traefik-ssl-certs:
    driver: local

services:
  keycloak-db:
    image: postgres:14.5
    env_file:
      - ./keycloak-postgres.env
    container_name: keycloak-db
    restart: unless-stopped
    volumes: 
      - ./keycloak-db:/var/lib/postgresql/data
    networks:
      - keycloak-network   
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.2
    restart: unless-stopped
    env_file:
      - ./keycloak-postgres.env
    entrypoint: /opt/keycloak/bin/kc.sh start --auto-build
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.entrypoints=web,websecure"
      - "traefik.http.routers.keycloak.rule=Host(`markus.jakobrathberger.eu`)"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.routers.keycloak.tls.certresolver=production"
    networks:
      - keycloak-network
    depends_on:
      - keycloak-db
  traefik:
    container_name: traefik
    image: traefik:v2.9.1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      # (Optional) Expose Dashboard
      # - "8080:8080"  # Don't do this in production!
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./traefik-ssl-certs:/ssl-certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - keycloak-network
networks:
  keycloak-network:
    driver: bridge